### ISSUE TITLE
Missing  "start_autoproxy_server.py"?

### ISSUE THREAD

**Issue by paulmueller** [cimatosa/jobmanager#24]
https://travis-ci.org/paulmueller/jobmanager/builds/62228829#L414

is there supposed to be a "start_autoproxy_server.py" in the tests directory?

**Comment by cimatosa** [comment]
YES, this is the reason why on test fails. For some reason I forgot to add this file to git! Damn it!

**Comment by cimatosa** [comment]
Ok, I think I know what the problem is. The test_exception is supposed to check if the catching of various errors, that could occur when connecting the Manager objects, works. In order to do so I also launch server and client using different python versions. The problem is now that the miniconda setup EITHER provides python2 OR python3. The error is mainly due to the fact, that the server running on python3 can not be started because it is missing numpy, while the test was tiggered using python2. and the other way around.

any ideas?

should on install two separate miniconda?

cheers

**Comment by cimatosa** [comment]
by the way, on my local setup, all tests pass, at least when running the test using python3

**Comment by paulmueller** [comment]
fixed it. we are now using two conda installations for testing.

**Comment by paulmueller** [comment]
https://travis-ci.org/cimatosa/jobmanager/jobs/77114024
